pdflatex ManualeUtente
makeglossaries ManualeUtente
pdflatex ManualeUtente
pdflatex ManualeUtente
pdflatex ManualeUtente
del ManualeUtente.aux
del ManualeUtente.glo
del ManualeUtente.glg
del ManualeUtente.gls
del ManualeUtente.ist
del ManualeUtente.log
del ManualeUtente.out
del ManualeUtente.lof
del ManualeUtente.toc
del diarioModificheMU.aux
